server:
  applicationConnectors:
  - type: http
    port: 5000

logging:
  level: INFO
  loggers:
    com.jointablec: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/TableC
  user: root
  properties:
    serverTimezone: UTC
    nullNamePatternMatchesAll: true